#!/usr/bin/env python3
"""Mirror GitLab merge-request commits into this repository as dated shadow commits.

GitHub's contribution graph only counts commits that live on GitHub, so this
script creates one small commit here for every commit the author made inside
a GitLab merge request they opened. Each shadow commit keeps the original
author date and links to the merge request, so the record is transparent.

Usage:
    python mirror.py                # import anything new
    python mirror.py --dry-run      # show what would be imported

Environment (all optional):
    GITLAB_USER_ID   GitLab numeric user id (default: 42048126)
    GITLAB_TOKEN     personal access token, only needed for private projects
    AUTHOR_EMAILS    comma-separated emails that count as "you" on GitLab
                     (default: the repo's git user.email)
    COMMIT_EMAIL     email to stamp on shadow commits; must be attached to
                     your GitHub account (default: the repo's git user.email)
"""
import json
import os
import subprocess
import sys
import urllib.parse
import urllib.request
from datetime import datetime, timezone

API = "https://gitlab.com/api/v4"
STATE_FILE = "imported.json"
LOG_FILE = "CONTRIBUTIONS.md"


def git(*args, env=None, check=True):
    return subprocess.run(["git", *args], check=check, capture_output=True, text=True, env=env).stdout.strip()


def api(path, **params):
    headers = {}
    token = os.environ.get("GITLAB_TOKEN")
    if token:
        headers["PRIVATE-TOKEN"] = token
    results = []
    page = 1
    while True:
        query = urllib.parse.urlencode({**params, "per_page": 100, "page": page})
        req = urllib.request.Request(f"{API}{path}?{query}", headers=headers)
        with urllib.request.urlopen(req) as resp:
            data = json.load(resp)
            next_page = resp.headers.get("x-next-page")
        results.extend(data)
        if not next_page:
            return results
        page = int(next_page)


def load_state():
    if os.path.exists(STATE_FILE):
        with open(STATE_FILE, encoding="utf-8") as fh:
            return json.load(fh)
    return {"imported": {}}


def save_state(state):
    with open(STATE_FILE, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(state, fh, indent=2, sort_keys=True)
        fh.write("\n")


def collect(user_id, author_emails):
    """Return {sha: record} for every commit by the author inside their MRs."""
    found = {}
    mrs = api("/merge_requests", author_id=user_id, scope="all", state="all")
    print(f"{len(mrs)} merge requests found")
    for mr in mrs:
        commits = api(f"/projects/{mr['project_id']}/merge_requests/{mr['iid']}/commits")
        for c in commits:
            if c["author_email"].lower() not in author_emails:
                continue
            if c["id"] in found:
                continue
            found[c["id"]] = {
                "sha": c["id"],
                "date": c["authored_date"],
                "title": c["title"],
                "project": mr["references"]["full"].split("!")[0],
                "mr_url": mr["web_url"],
                "mr_state": mr["state"],
            }
    return found


def shadow_commit(rec, commit_email):
    date = rec["date"]
    day = date[:10]
    line = f"- {day} · {rec['project']} · [{rec['title']}]({rec['mr_url']}) · `{rec['sha'][:8]}`\n"
    with open(LOG_FILE, "a", encoding="utf-8", newline="\n") as fh:
        fh.write(line)
    env = dict(os.environ, GIT_AUTHOR_DATE=date, GIT_COMMITTER_DATE=date,
               GIT_AUTHOR_EMAIL=commit_email, GIT_COMMITTER_EMAIL=commit_email)
    message = (
        f"{rec['project']}: {rec['title']}\n\n"
        f"Mirror of GitLab commit {rec['sha']}\n"
        f"Merge request: {rec['mr_url']}\n"
    )
    git("add", LOG_FILE, STATE_FILE)
    git("commit", "-q", "-m", message, env=env)


def main():
    dry_run = "--dry-run" in sys.argv
    user_id = os.environ.get("GITLAB_USER_ID", "42048126")
    default_email = git("config", "user.email")
    author_emails = {e.strip().lower() for e in os.environ.get("AUTHOR_EMAILS", default_email).split(",")}
    commit_email = os.environ.get("COMMIT_EMAIL", default_email)

    state = load_state()
    found = collect(user_id, author_emails)
    new = [r for sha, r in found.items() if sha not in state["imported"]]
    new.sort(key=lambda r: r["date"])
    print(f"{len(found)} commits by you, {len(new)} not yet mirrored")

    if not os.path.exists(LOG_FILE):
        with open(LOG_FILE, "w", encoding="utf-8", newline="\n") as fh:
            fh.write("# GitLab contributions\n\nOne line per commit authored inside a GitLab merge request. "
                     "Generated by `mirror.py`; newest at the bottom.\n\n")

    for rec in new:
        print(f"{rec['date'][:10]}  {rec['project']:<45} {rec['title'][:60]}")
        if dry_run:
            continue
        state["imported"][rec["sha"]] = {"date": rec["date"], "mr_url": rec["mr_url"]}
        save_state(state)
        shadow_commit(rec, commit_email)

    if not dry_run and new:
        print(f"created {len(new)} commits; last import {datetime.now(timezone.utc).isoformat()}")


if __name__ == "__main__":
    main()
